---
- name: docker test
  hosts: docker-test
  become: true
  tasks:
    - name: remove old docker 
      yum:
        name: "{{ item }}"
        state: absent
      with_items: 
        - "docker"
        - "docker-common"
        - "docker-selinux"
        - "docker-engine-selinux"
        - "docker-engine"
        - "docker-ce"
    - name: update yum
      yum:
        update_only: yes
        update_cache: yes
    - name: install epel-release repo
      yum:
        name: epel-release
    - name: install additional needed packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - "yum-utils"
        - "device-mapper-persistent-data"
        - "lvm2"
   
    - name: download docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/
        mode: '0700'
    - name: update yum
      yum:
        update_only: yes
        update_cache: yes
    - name: install dockere
      yum:
        name: docker-ce
        state: present